/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Model.Observer;
import Model.PeerNode;
import java.awt.BorderLayout;
import java.awt.Color;
import java.net.InetAddress;
import java.util.Iterator;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.border.Border;

/**
 *
 * @author Adam
 */
public class MainUI extends javax.swing.JFrame implements Observer {

    private PeerNode node;
    private JPanel peerPnl;
    private JPanel contentPnl;
    private JPanel filePnl;
    private JTextArea fileTxtArea;
    private JList fileList;
    private JToolBar toolBar;
    private JButton getBtn;
    private JButton disconnectBtn;
    private JButton putBtn;
    private JTextField searchFld;
    private JButton searchBtn;
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setSize(800,800);
        contentPnl = new JPanel();
        contentPnl.setLayout(new BorderLayout());
        toolBar = new JToolBar();
        getBtn = new JButton("GET");
        putBtn = new JButton("PUT");
        disconnectBtn = new JButton("Disconnect");
        searchBtn = new JButton("Search");
        searchFld = new JTextField();
        searchFld.setSize(100, WIDTH);
        searchFld.setToolTipText("Search...");
        toolBar.add(getBtn);
        toolBar.add(putBtn);
        toolBar.add(disconnectBtn);
        toolBar.add(searchFld);
        toolBar.add(searchBtn);
        toolBar.setFloatable(false);
        filePnl = new JPanel();
        filePnl.setBorder(BorderFactory.createLineBorder(Color.black));
//        fileTxtArea = new JTextArea(); 
        //TO DO : add file names from peers to JList for selection
        fileList = new JList();
        filePnl.add(fileList);
        peerPnl = new JPanel();
        peerPnl.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        contentPnl.add(toolBar, BorderLayout.NORTH);
        contentPnl.add(peerPnl, BorderLayout.WEST);
        contentPnl.add(filePnl, BorderLayout.CENTER);
        this.add(contentPnl);
    }

    public void setNode(PeerNode node)  {
        this.node = node;
        node.register(this);
    }
    
    @Override
    public void update(Map<InetAddress, PeerNode> peers) {
        peerPnl.removeAll();
        Iterator it = peers.values().iterator();
        while (it.hasNext())   {
            String str = it.next().toString();
            System.out.println(str);
            JLabel pTxt = new JLabel(str);
            peerPnl.add(pTxt);
        }
        peerPnl.repaint();
        this.revalidate();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMnu = new javax.swing.JMenu();
        exitItm = new javax.swing.JMenuItem();
        editMnu = new javax.swing.JMenu();
        settingsItm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMnu.setText("File");

        exitItm.setText("Exit");
        exitItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItmActionPerformed(evt);
            }
        });
        fileMnu.add(exitItm);

        menuBar.add(fileMnu);

        editMnu.setText("Edit");

        settingsItm.setText("Settings");
        editMnu.add(settingsItm);

        menuBar.add(editMnu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItmActionPerformed
        node.stop();
        dispose();
    }//GEN-LAST:event_exitItmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMnu;
    private javax.swing.JMenuItem exitItm;
    private javax.swing.JMenu fileMnu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem settingsItm;
    // End of variables declaration//GEN-END:variables

    
}
